#!/bin/bash

# Large Files Git Resolution Script
# Date: 16/06/2025 18:58:45
# Purpose: Remove large files from git tracking to enable pushing

echo "=== Starting Large Files Resolution ==="
echo "This script will remove large files from git tracking"
echo ""

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo "Error: Not in a git repository"
    exit 1
fi

echo "Step 1: Removing zip files from tracking..."
git rm --cached data/f45bkkt8pr-1.zip 2>/dev/null || echo "Zip file already removed or not tracked"

echo "Step 2: Removing .joblib model files from tracking..."
find models/ -name "*.joblib" -exec git rm --cached {} \; 2>/dev/null
find data/ -name "*.joblib" -exec git rm --cached {} \; 2>/dev/null

echo "Step 3: Removing .pkl feature files from tracking..."
find data/features/ -name "*.pkl" -exec git rm --cached {} \; 2>/dev/null
find data/clean/features/ -name "*.pkl" -exec git rm --cached {} \; 2>/dev/null

echo "Step 4: Checking current git status..."
git status

echo ""
echo "Step 5: Adding updated .gitignore..."
git add .gitignore

echo ""
echo "Step 6: Creating commit to remove large files..."
git commit -m "Remove large model and data files from tracking

- Removed .joblib model files from all subdirectories
- Removed .pkl feature files
- Removed zip data files
- Updated .gitignore with comprehensive patterns
- These files can be regenerated from code"

echo ""
echo "Step 7: Checking repository size..."
echo "Repository size before cleanup:"
du -sh .git/

echo ""
echo "Step 8: Running git garbage collection to reduce size..."
git gc --aggressive --prune=now

echo ""
echo "Repository size after cleanup:"
du -sh .git/

echo ""
echo "=== Resolution Complete ==="
echo "You should now be able to push to the remote repository"
echo "Run: git push origin notebooks"
echo ""
echo "Note: Model and feature files will need to be regenerated by running the training scripts" 